defaults:
  extension:
    - .avi
    - .mp4
    - .mkv
  format: '%n - %s%e - %t%x'
  ignore:
    - .DS_Store
    - thumbs.db
  library: thetvdb
  organise: yes
  renamed: /mnt/media/TV/
  the: true

'24':
  format: '%n - %s%e'

american dad:
  canonical: American Dad!

archer 2009:
  canonical: Archer (2009)

castle 2009:
  canonical: Castle (2009)

csi:
  canonical: 'CSI: Crime Scene Investigation'
  output: 'CSI, Crime Scene Investigation'

doctor who 2005:
  canonical: Doctor Who (2005)

'highlander - the animated series':
  canonical: 'Highlander: The Animated Series'
  format: '%n.-.%sx%e.-.'

'the newsroom 2012':
  canonical: The Newsroom (2012)

'star trek voyager':
  canonical: 'Star Trek: Voyager'

"the avengers earths mightiest heroes":
  canonical: "The Avengers: Earth's Mightiest Heroes"

the it crowd:
  the: false

the killing:
  canonical: The Killing (2011)

the simpsons:
  the: false

thundercats 2011:
  canonical: ThunderCats (2011)

