import logging
import os
import time
from git import *

log = logging.getLogger('pag.worker')


def worker(queue, working_dir, git_path):
    repo = Repo(git_path)
    index = repo.index
    while True:
        original_item = queue.get()
        if os.path.isfile(original_item):
            item = os.path.split(original_item)[1]
        log.debug('Found: {0}'.format(item))
        try:
            index.add([original_item])
            index.write()
            commit = index.commit('auto-generated by pag')
        except Exception as e:
            for msg in e.args:
                kwargs = {'type': e.__repr__()[:e.__repr__().index('(')], 'error': msg}
                log.critical('{type}: {error}'.format(**kwargs))
            continue
        time.sleep(1)  # don't use 100% cpu
        queue.task_done()

